# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('desired_rating', models.IntegerField()),
                ('opening_time', models.IntegerField()),
                ('closing_time', models.IntegerField()),
                ('distance', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
