# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dine',
            new_name='Dine_query',
        ),
    ]
