# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_dine_query_current_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dine_query',
            name='name',
        ),
    ]
