# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_dine_query_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dine_query',
            name='distance',
        ),
        migrations.AddField(
            model_name='dine_query',
            name='terms',
            field=models.CharField(default='sexy romantic', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dine_query',
            name='transport_by',
            field=models.CharField(choices=[('driving', 'driving'), ('walking', 'walking'), ('bicycling', 'bicycling'), ('transit', 'transit')], default='driving', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='desired_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='price',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
