# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_dine_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dine_query',
            name='transport_by',
            field=models.CharField(choices=[('driving', 'driving'), ('walking', 'walking'), ('bicycling', 'bicycling'), ('transit', 'transit')], default='Driving', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='closing_time',
            field=models.IntegerField(default=2400),
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='opening_time',
            field=models.IntegerField(default=600),
        ),
    ]
