# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20160305_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dine_query',
            name='distance',
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='closing_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='desired_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='opening_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dine_query',
            name='price',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
