# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20160305_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='dine_query',
            name='terms',
            field=models.CharField(default=' butter chicken sexy', max_length=150),
            preserve_default=False,
        ),
    ]
