# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_dine_query_terms'),
        ('restaurants', '0008_auto_20160306_2058'),
    ]

    operations = [
    ]
