# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dine_query',
            name='distance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
