# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_dine_query_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dine_query',
            name='distance',
        ),
    ]
